### PR TITLE
feature: Decaffeinate

### PR DESCRIPTION
**Pull request by icirellik**
Decaffeinates passport and enables all of the unit tests that were
accidentally disabled a few years ago.

Published in [review app](HTTP://novo.artsy.net)

<details>
  <summary>📦 Published PR as canary version: <code>2.0.1-canary.163.329.0</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```sh
  npm install @artsy/passport@2.0.1-canary.163.329.0
  # or 
  yarn add @artsy/passport@2.0.1-canary.163.329.0
  ```
</details>

### CODE REVIEW

**Review by joeyAghion — APPROVED** [review]
Could you highlight which change reenables tests?

**Comment by icirellik** [comment]
@joeyAghion removing an `only` that was added a long time ago 😅 

https://github.com/artsy/artsy-passport/blob/master/test/app/lifecycle.coffee#L79

**Review by mc-jones — APPROVED** [review]

**Comment by mc-jones** [comment]
@icirellik - LGTM, but considering the size, any potential concerns from your end?

**Comment by icirellik** [comment]
@mc-jones no concerns on my end, decaffeination is 99% the same as running the CoffeeScript compiler, since that is what it does. 😄

**Comment by artsyit** [comment]
:rocket: PR was released in [`v3.0.0`](https://github.com/artsy/artsy-passport/releases/tag/v3.0.0) :rocket:

**Pull request merged**
